
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk

ASSETS_PATH = Path(__file__).parent / "assets" / "frame0"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


import sys

window = Tk()
window.title('Calculator')

# Determine base path (works for .py and .exe)
if getattr(sys, 'frozen', False):
    BASE_PATH = Path(sys._MEIPASS)
else:
    BASE_PATH = Path(__file__).parent

# Load logo safely from correct path
logo_path = BASE_PATH / "logo.png"
icon = tk.PhotoImage(file=logo_path)
window.iconphoto(False, icon)


window.geometry("227x424")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 424,
    width = 227,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    113.5,
    62.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#000000",
    fg="#ffffff",
    highlightthickness=0,
    font=("Helvetica", 16),
)
entry_1.place(
    x=15.0,
    y=10.0,
    width=197.0,
    height=102.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_clear(),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_1.place(
    x=21.0,
    y=125.0,
    width=41.0,
    height=41.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(7),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_2.place(
    x=21.0,
    y=177.0,
    width=41.0,
    height=41.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(4),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_3.place(
    x=21.0,
    y=229.0,
    width=41.0,
    height=41.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(1),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_4.place(
    x=21.0,
    y=281.0,
    width=41.0,
    height=41.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_plus_minus(),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_5.place(
    x=69.0,
    y=125.0,
    width=41.0,
    height=41.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(8),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_6.place(
    x=69.0,
    y=177.0,
    width=41.0,
    height=41.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(5),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_7.place(
    x=69.0,
    y=229.0,
    width=41.0,
    height=41.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(2),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_8.place(
    x=69.0,
    y=281.0,
    width=41.0,
    height=41.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handel_percentage(),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_9.place(
    x=117.0,
    y=125.0,
    width=41.0,
    height=41.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(9),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_10.place(
    x=117.0,
    y=177.0,
    width=41.0,
    height=41.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(6),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_11.place(
    x=117.0,
    y=229.0,
    width=41.0,
    height=41.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(3),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_12.place(
    x=117.0,
    y=281.0,
    width=41.0,
    height=41.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_decimal(),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_13.place(
    x=117.0,
    y=333.0,
    width=41.0,
    height=41.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click('/'),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_14.place(
    x=165.0,
    y=125.0,
    width=41.0,
    height=41.0
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click('*'),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_15.place(
    x=165.0,
    y=177.0,
    width=41.0,
    height=41.0
)

button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click('-'),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_16.place(
    x=165.0,
    y=229.0,
    width=41.0,
    height=41.0
)

button_image_17 = PhotoImage(
    file=relative_to_assets("button_17.png"))
button_17 = Button(
    image=button_image_17,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click('+'),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_17.place(
    x=165.0,
    y=281.0,
    width=41.0,
    height=41.0
)

button_image_18 = PhotoImage(
    file=relative_to_assets("button_18.png"))
button_18 = Button(
    image=button_image_18,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_equal(),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_18.place(
    x=165.0,
    y=333.0,
    width=41.0,
    height=41.0
)

button_image_19 = PhotoImage(
    file=relative_to_assets("button_19.png"))
button_19 = Button(
    image=button_image_19,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: handle_btn_click(0),
    relief="flat",
    bg='#000000',
    activebackground='#000000'
)
button_19.place(
    x=21.0,
    y=333.0,
    width=85.0,
    height=41.0
)
def handle_btn_click(value):
    entry_1.insert(tk.END, str(value))

def handle_equal():
    exp = entry_1.get()
    ans = eval(exp)
    entry_1.delete(0, tk.END)
    entry_1.insert(tk.END, str(ans))

def handle_clear():
    entry_1.delete(0, tk.END)

def handel_percentage():
    try:
        value = float(entry_1.get())
        entry_1.delete(0, tk.END)
        entry_1.insert(tk.END, str(value / 100))
    except:
        entry_1.delete(0, tk.END)
        entry_1.insert(tk.END, '0')

def handle_decimal():
    current = entry_1.get()
    # Only allow one dot in the current number
    if '.' not in current.split()[-1]:
        entry_1.insert(tk.END, '.')

def handle_plus_minus():
    current = entry_1.get()
    if current.startswith('-'):
        entry_1.delete(0)
    else:
        entry_1.insert(0, '-')

window.resizable(False, False)
window.mainloop()
